### ISSUE TITLE
Github Pages: set basename in HashRouter 

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon-ui#31]
We also need to specify the `basename` to bein able to redirect the link correctly, we already inject the PUBLIC_URL as env variable, we can infer the basename from there

https://stackoverflow.com/a/48135905

https://v5.reactrouter.com/web/api/HashRouter/basename-string

**Comment by Janaka-Steph** [comment]
Did you have a link that doesn't work? 
App is using React Router v6 now and I think `basename` is not necessary anymore. 
They don't mention basename explicitly but I think it is related to this: https://reactrouter.com/docs/en/v6/upgrading/v5#relative-routes-and-links

**Comment by tiero** [comment]
If you click on settings wheel or the main logo
